;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 2.0.11
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(in-package :nanomsg)



(cl:defconstant #.(lispify "NN_VERSION_CURRENT" 'constant) 2)

(cl:defconstant #.(lispify "NN_VERSION_REVISION" 'constant) 0)

(cl:defconstant #.(lispify "NN_VERSION_AGE" 'constant) 2)

(cl:defconstant #.(lispify "NN_HAUSNUMERO" 'constant) 156384712)

(cl:defconstant #.(lispify "ENOTSUP" 'constant) (cl:+ 156384712 1))

(cl:defconstant #.(lispify "EPROTONOSUPPORT" 'constant) (cl:+ 156384712 2))

(cl:defconstant #.(lispify "ENOBUFS" 'constant) (cl:+ 156384712 3))

(cl:defconstant #.(lispify "ENETDOWN" 'constant) (cl:+ 156384712 4))

(cl:defconstant #.(lispify "EADDRINUSE" 'constant) (cl:+ 156384712 5))

(cl:defconstant #.(lispify "EADDRNOTAVAIL" 'constant) (cl:+ 156384712 6))

(cl:defconstant #.(lispify "ECONNREFUSED" 'constant) (cl:+ 156384712 7))

(cl:defconstant #.(lispify "EINPROGRESS" 'constant) (cl:+ 156384712 8))

(cl:defconstant #.(lispify "ENOTSOCK" 'constant) (cl:+ 156384712 9))

(cl:defconstant #.(lispify "EAFNOSUPPORT" 'constant) (cl:+ 156384712 10))

(cl:defconstant #.(lispify "EPROTO" 'constant) (cl:+ 156384712 11))

(cl:defconstant #.(lispify "EAGAIN" 'constant) (cl:+ 156384712 12))

(cl:defconstant #.(lispify "EBADF" 'constant) (cl:+ 156384712 13))

(cl:defconstant #.(lispify "EINVAL" 'constant) (cl:+ 156384712 14))

(cl:defconstant #.(lispify "EMFILE" 'constant) (cl:+ 156384712 15))

(cl:defconstant #.(lispify "EFAULT" 'constant) (cl:+ 156384712 16))

(cl:defconstant #.(lispify "EACCES" 'constant) (cl:+ 156384712 17))

(cl:defconstant #.(lispify "EACCESS" 'constant) (cl:+ 156384712 17))

(cl:defconstant #.(lispify "ENETRESET" 'constant) (cl:+ 156384712 18))

(cl:defconstant #.(lispify "ENETUNREACH" 'constant) (cl:+ 156384712 19))

(cl:defconstant #.(lispify "EHOSTUNREACH" 'constant) (cl:+ 156384712 20))

(cl:defconstant #.(lispify "ENOTCONN" 'constant) (cl:+ 156384712 21))

(cl:defconstant #.(lispify "EMSGSIZE" 'constant) (cl:+ 156384712 22))

(cl:defconstant #.(lispify "ETIMEDOUT" 'constant) (cl:+ 156384712 23))

(cl:defconstant #.(lispify "ECONNABORTED" 'constant) (cl:+ 156384712 24))

(cl:defconstant #.(lispify "ECONNRESET" 'constant) (cl:+ 156384712 25))

(cl:defconstant #.(lispify "ENOPROTOOPT" 'constant) (cl:+ 156384712 26))

(cl:defconstant #.(lispify "EISCONN" 'constant) (cl:+ 156384712 27))

(cl:defconstant #.(lispify "ESOCKTNOSUPPORT" 'constant) (cl:+ 156384712 28))

(cl:defconstant #.(lispify "ETERM" 'constant) (cl:+ 156384712 53))

(cl:defconstant #.(lispify "EFSM" 'constant) (cl:+ 156384712 54))

(cffi:defcfun ("nn_errno" #.(lispify "nn_errno" 'function)) :int)

(cffi:defcfun ("nn_strerror" #.(lispify "nn_strerror" 'function)) :string
  (errnum :int))

(cffi:defcfun ("nn_symbol" #.(lispify "nn_symbol" 'function)) :string
  (i :int)
  (value :pointer))

(cl:defconstant #.(lispify "NN_NS_NAMESPACE" 'constant) 0)

(cl:defconstant #.(lispify "NN_NS_VERSION" 'constant) 1)

(cl:defconstant #.(lispify "NN_NS_DOMAIN" 'constant) 2)

(cl:defconstant #.(lispify "NN_NS_TRANSPORT" 'constant) 3)

(cl:defconstant #.(lispify "NN_NS_PROTOCOL" 'constant) 4)

(cl:defconstant #.(lispify "NN_NS_OPTION_LEVEL" 'constant) 5)

(cl:defconstant #.(lispify "NN_NS_SOCKET_OPTION" 'constant) 6)

(cl:defconstant #.(lispify "NN_NS_TRANSPORT_OPTION" 'constant) 7)

(cl:defconstant #.(lispify "NN_NS_OPTION_TYPE" 'constant) 8)

(cl:defconstant #.(lispify "NN_NS_OPTION_UNIT" 'constant) 9)

(cl:defconstant #.(lispify "NN_NS_FLAG" 'constant) 10)

(cl:defconstant #.(lispify "NN_NS_ERROR" 'constant) 11)

(cl:defconstant #.(lispify "NN_NS_LIMIT" 'constant) 12)

(cl:defconstant #.(lispify "NN_TYPE_NONE" 'constant) 0)

(cl:defconstant #.(lispify "NN_TYPE_INT" 'constant) 1)

(cl:defconstant #.(lispify "NN_TYPE_STR" 'constant) 2)

(cl:defconstant #.(lispify "NN_UNIT_NONE" 'constant) 0)

(cl:defconstant #.(lispify "NN_UNIT_BYTES" 'constant) 1)

(cl:defconstant #.(lispify "NN_UNIT_MILLISECONDS" 'constant) 2)

(cl:defconstant #.(lispify "NN_UNIT_PRIORITY" 'constant) 3)

(cl:defconstant #.(lispify "NN_UNIT_BOOLEAN" 'constant) 4)

(cffi:defcstruct #.(lispify "nn_symbol_properties" 'classname)
	(#.(lispify "value" 'slotname) :int)
	(#.(lispify "name" 'slotname) :string)
	(#.(lispify "ns" 'slotname) :int)
	(#.(lispify "type" 'slotname) :int)
	(#.(lispify "unit" 'slotname) :int))

(cffi:defcfun ("nn_symbol_info" #.(lispify "nn_symbol_info" 'function)) :int
  (i :int)
  (buf :pointer)
  (buflen :int))

(cffi:defcfun ("nn_term" #.(lispify "nn_term" 'function)) :void)

(cffi:defcfun ("nn_allocmsg" #.(lispify "nn_allocmsg" 'function)) :pointer
  (size :unsigned-int)
  (type :int))

(cffi:defcfun ("nn_reallocmsg" #.(lispify "nn_reallocmsg" 'function)) :pointer
  (msg :pointer)
  (size :unsigned-int))

(cffi:defcfun ("nn_freemsg" #.(lispify "nn_freemsg" 'function)) :int
  (msg :pointer))

(cffi:defcstruct #.(lispify "nn_iovec" 'classname)
	(#.(lispify "iov_base" 'slotname) :pointer)
	(#.(lispify "iov_len" 'slotname) :unsigned-int))

(cffi:defcstruct #.(lispify "nn_msghdr" 'classname)
	(#.(lispify "msg_iov" 'slotname) :pointer)
	(#.(lispify "msg_iovlen" 'slotname) :int)
	(#.(lispify "msg_control" 'slotname) :pointer)
	(#.(lispify "msg_controllen" 'slotname) :unsigned-int))

(cffi:defcstruct #.(lispify "nn_cmsghdr" 'classname)
	(#.(lispify "cmsg_len" 'slotname) :unsigned-int)
	(#.(lispify "cmsg_level" 'slotname) :int)
	(#.(lispify "cmsg_type" 'slotname) :int))

(cffi:defcfun ("nn_cmsg_nexthdr_" #.(lispify "nn_cmsg_nexthdr_" 'function)) :pointer
  (mhdr :pointer)
  (cmsg :pointer))

(cl:defconstant #.(lispify "AF_SP" 'constant) 1)

(cl:defconstant #.(lispify "AF_SP_RAW" 'constant) 2)

(cl:defconstant #.(lispify "NN_SOCKADDR_MAX" 'constant) 128)

(cl:defconstant #.(lispify "NN_SOL_SOCKET" 'constant) 0)

(cl:defconstant #.(lispify "NN_LINGER" 'constant) 1)

(cl:defconstant #.(lispify "NN_SNDBUF" 'constant) 2)

(cl:defconstant #.(lispify "NN_RCVBUF" 'constant) 3)

(cl:defconstant #.(lispify "NN_SNDTIMEO" 'constant) 4)

(cl:defconstant #.(lispify "NN_RCVTIMEO" 'constant) 5)

(cl:defconstant #.(lispify "NN_RECONNECT_IVL" 'constant) 6)

(cl:defconstant #.(lispify "NN_RECONNECT_IVL_MAX" 'constant) 7)

(cl:defconstant #.(lispify "NN_SNDPRIO" 'constant) 8)

(cl:defconstant #.(lispify "NN_RCVPRIO" 'constant) 9)

(cl:defconstant #.(lispify "NN_SNDFD" 'constant) 10)

(cl:defconstant #.(lispify "NN_RCVFD" 'constant) 11)

(cl:defconstant #.(lispify "NN_DOMAIN" 'constant) 12)

(cl:defconstant #.(lispify "NN_PROTOCOL" 'constant) 13)

(cl:defconstant #.(lispify "NN_IPV4ONLY" 'constant) 14)

(cl:defconstant #.(lispify "NN_SOCKET_NAME" 'constant) 15)

(cl:defconstant #.(lispify "NN_DONTWAIT" 'constant) 1)

(cffi:defcfun ("nn_socket" #.(lispify "nn_socket" 'function)) :int
  (domain :int)
  (protocol :int))

(cffi:defcfun ("nn_close" #.(lispify "nn_close" 'function)) :int
  (s :int))

(cffi:defcfun ("nn_setsockopt" #.(lispify "nn_setsockopt" 'function)) :int
  (s :int)
  (level :int)
  (option :int)
  (optval :pointer)
  (optvallen :unsigned-int))

(cffi:defcfun ("nn_getsockopt" #.(lispify "nn_getsockopt" 'function)) :int
  (s :int)
  (level :int)
  (option :int)
  (optval :pointer)
  (optvallen :pointer))

(cffi:defcfun ("nn_bind" #.(lispify "nn_bind" 'function)) :int
  (s :int)
  (addr :string))

(cffi:defcfun ("nn_connect" #.(lispify "nn_connect" 'function)) :int
  (s :int)
  (addr :string))

(cffi:defcfun ("nn_shutdown" #.(lispify "nn_shutdown" 'function)) :int
  (s :int)
  (how :int))

(cffi:defcfun ("nn_send" #.(lispify "nn_send" 'function)) :int
  (s :int)
  (buf :pointer)
  (len :unsigned-int)
  (flags :int))

(cffi:defcfun ("nn_recv" #.(lispify "nn_recv" 'function)) :int
  (s :int)
  (buf :pointer)
  (len :unsigned-int)
  (flags :int))

(cffi:defcfun ("nn_sendmsg" #.(lispify "nn_sendmsg" 'function)) :int
  (s :int)
  (msghdr :pointer)
  (flags :int))

(cffi:defcfun ("nn_recvmsg" #.(lispify "nn_recvmsg" 'function)) :int
  (s :int)
  (msghdr :pointer)
  (flags :int))

(cl:defconstant #.(lispify "NN_POLLIN" 'constant) 1)

(cl:defconstant #.(lispify "NN_POLLOUT" 'constant) 2)

(cffi:defcstruct #.(lispify "nn_pollfd" 'classname)
	(#.(lispify "fd" 'slotname) :int)
	(#.(lispify "events" 'slotname) :short)
	(#.(lispify "revents" 'slotname) :short))

(cffi:defcfun ("nn_poll" #.(lispify "nn_poll" 'function)) :int
  (fds :pointer)
  (nfds :int)
  (timeout :int))

(cffi:defcfun ("nn_device" #.(lispify "nn_device" 'function)) :int
  (s1 :int)
  (s2 :int))

(cl:defconstant #.(lispify "NN_PROTO_BUS" 'constant) 7)

(cl:defconstant #.(lispify "NN_BUS" 'constant) (cl:* 7 (cl:+ 16 0)))

(cl:defconstant #.(lispify "NN_INPROC" 'constant) -1)

(cl:defconstant #.(lispify "NN_IPC" 'constant) -2)

(cl:defconstant #.(lispify "NN_PROTO_PAIR" 'constant) 1)

(cl:defconstant #.(lispify "NN_PAIR" 'constant) (cl:* 1 (cl:+ 16 0)))

(cl:defconstant #.(lispify "NN_PROTO_PIPELINE" 'constant) 5)

(cl:defconstant #.(lispify "NN_PUSH" 'constant) (cl:* 5 (cl:+ 16 0)))

(cl:defconstant #.(lispify "NN_PULL" 'constant) (cl:* 5 (cl:+ 16 1)))

(cl:defconstant #.(lispify "NN_PROTO_PUBSUB" 'constant) 2)

(cl:defconstant #.(lispify "NN_PUB" 'constant) (cl:* 2 (cl:+ 16 0)))

(cl:defconstant #.(lispify "NN_SUB" 'constant) (cl:* 2 (cl:+ 16 1)))

(cl:defconstant #.(lispify "NN_SUB_SUBSCRIBE" 'constant) 1)

(cl:defconstant #.(lispify "NN_SUB_UNSUBSCRIBE" 'constant) 2)

(cl:defconstant #.(lispify "NN_PROTO_REQREP" 'constant) 3)

(cl:defconstant #.(lispify "NN_REQ" 'constant) (cl:* 3 (cl:+ 16 0)))

(cl:defconstant #.(lispify "NN_REP" 'constant) (cl:* 3 (cl:+ 16 1)))

(cl:defconstant #.(lispify "NN_REQ_RESEND_IVL" 'constant) 1)

(cffi:defcunion #.(lispify "nn_req_handle" 'classname)
	(#.(lispify "i" 'slotname) :int)
	(#.(lispify "ptr" 'slotname) :pointer))

(cffi:defcfun ("nn_req_send" #.(lispify "nn_req_send" 'function)) :int
  (s :int)
  (hndl #.(lispify "nn_req_handle" 'classname))
  (buf :pointer)
  (len :unsigned-int)
  (flags :int))

(cffi:defcfun ("nn_req_recv" #.(lispify "nn_req_recv" 'function)) :int
  (s :int)
  (hndl :pointer)
  (buf :pointer)
  (len :unsigned-int)
  (flags :int))

(cl:defconstant #.(lispify "NN_PROTO_SURVEY" 'constant) 6)

(cl:defconstant #.(lispify "NN_SURVEYOR" 'constant) (cl:* 6 (cl:+ 16 0)))

(cl:defconstant #.(lispify "NN_RESPONDENT" 'constant) (cl:* 6 (cl:+ 16 1)))

(cl:defconstant #.(lispify "NN_SURVEYOR_DEADLINE" 'constant) 1)

(cl:defconstant #.(lispify "NN_TCP" 'constant) -3)

(cl:defconstant #.(lispify "NN_TCP_NODELAY" 'constant) 1)


